# Site
repository: danifranco/danifranco.github.io
favicon: images/favicon2.png

# Personal info
name: Daniel Franco-Barranco
title: HPC System Administrator and PhD Student 
email: daniel.franco@dipc.org
#website: www.github.com/danifranco

# Social links
twitter_username: danifranco93
github_username:  danifranco
schoolar_username: jVEfpY4AAAAJ
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: daniel-franco-barranco-99936596
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Daniel and I'm half-time <mark>HPC System Administrator</mark> at Donostia International Physics Center (DIPC), being part of the management and configuration of the biggest cluster of the Basque Country. The other half of my workday I'm a <mark>PhD Student</mark> at the University of the Basque Country, together with the DIPC, supervised by Ignacio Arganda-Carreras and Arrate Mu√±oz-Barrutia. 
  
  My general research area is in Biomedical image processing and Computer Vision, focused in the design and development of novel Deep Learning solutions for the segmentation of organelles in large Electron microscope images and across microscope types and modalities.

# Experience Section
experience_title: Publications

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme
# remote_theme: danifranco/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
